defaultBaseImage: build-harbor.alauda.cn/ops/alpine:3.20.6-alauda-202502271510
baseImageOverrides:
  # renovate: datasource=docker
  github.com/my-user/my-repo/cmd/app: build-harbor.alauda.cn/ops/alpine:3.20.6-alauda-202502271510
  # renovate: datasource=docker
  github.com/my-user/my-repo/cmd/foo: docker-mirrors.alauda.cn/library/eclipse-temurin:17.0.10_7-jre-jammy